package refactored.domain;

public enum CheckType {
    TOO_MANY_ARGUMENTS,
    PUBLIC_NON_FINAL_FIELD,
    UNUSED_PRIVATE_METHOD,
    METHOD_NAME_APPROPRIATENESS,
    CIRCULAR_DEPENDENCY,
    CONCRETE_DEPENDENCY
}
